name: "Setup"
description: "Setup tooling"
runs:
  using: "composite"
  steps:
    - name: Install and setup Dojo
      run: |
        set -e
        curl -L https://install.dojoengine.org | bash
        source "$HOME/.config/.dojo/env"
        dojoup install ${{ env.DOJO_VERSION }}

        if [ ! -f "$HOME/.config/.dojo/installed/toolchain/${{ env.DOJO_VERSION }}/katana" ]; then
          echo "Katana not found after installation"
          ls -al "$HOME/.config/.dojo/installed/toolchain/${{ env.DOJO_VERSION }}/"
          exit 1
        fi

        sudo mv "$HOME/.config/.dojo/installed/toolchain/${{ env.DOJO_VERSION }}/katana" /usr/local/bin/
        sudo mv "$HOME/.config/.dojo/installed/toolchain/${{ env.DOJO_VERSION }}/sozo" /usr/local/bin/
      shell: bash
    # - name: Install dojoup
    #   run: curl -L https://install.dojoengine.org | bash
    #   shell: bash

    # - name: Install dojo
    #   run: |
    #     /home/runner/.config/.dojo/bin/dojoup install ${{ env.DOJO_VERSION }}
    #     sudo mv /home/runner/.config/.dojo/installed/toolchain/${{ env.DOJO_VERSION }}/katana /usr/local/bin/
    #     sudo mv /home/runner/.config/.dojo/installed/toolchain/${{ env.DOJO_VERSION }}/sozo /usr/local/bin/
    #   shell: bash
