name: "Setup"
description: "Setup tooling"
runs:
  using: "composite"
  steps:
    - name: Install dojoup
      run: curl -L https://install.dojoengine.org | bash
      shell: bash

    - name: Install dojo
      run: |
        /home/runner/.config/.dojo/bin/dojoup install ${{ env.DOJO_VERSION }}
        sudo mv /home/runner/.config/.dojo/installed/toolchain/${{ env.DOJO_VERSION }}/katana /usr/local/bin/
        sudo mv /home/runner/.config/.dojo/installed/toolchain/${{ env.DOJO_VERSION }}/sozo /usr/local/bin/
      shell: bash
