[world]
name = ">LORE Starknet"
description = "> get started with LORE Starknet"
seed = "lore_sn_0_2_1"

[namespace]
default = "lore_sn"

[env]
rpc_url = "http://localhost:5050/"
slot_name = "lore_sn-stage"

world_address = "0x05c43099eee9d89488d20337155242a5110e926024e38a75f9ac99766f77e7d2"
account_address = "0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec"
private_key = "0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912"

[writers]
"lore_sn" = ["lore_sn-setup", "lore_sn-permit_token"]

[init_call_args]
"lore_sn-setup" = [
  "0x0", # messaging/piltover address
  "0x0", # appchain address
  "0x0", # cartridge address
]

[migration]
skip_contracts = [
  "fact_registry_mock", # deployed manually
]
