[world]
name = ">LORE Starknet"
description = "> get started with LORE Starknet"
seed = "lore_sn_0_2_0"

[namespace]
default = "lore_sn"

[env]
rpc_url = "https://api.cartridge.gg/x/starknet/sepolia/rpc/v0_9"
slot_name = "lore_sn-stage"
settlement_chain_id = "SN_SEPOLIA"
appchain_id = "lore_appchain"
core_contract_address = "0x9496013cd0ffc7111c6c8358830d0f0453615b56f99a1258781301c90401ab"
core_contract_deployed_block = "6881095"
fact_registry_address = "0x07d3550237ecf2d6ddef9b78e59b38647ee511467fe000ce276f245a006b40bc"

world_address = "0x0757293bbab55927b8990fc154a8b3e758a66e6ccb3f38ab701aa1f2e91f1f24"
# account_address = "0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec"
# private_key = "0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912"

[writers]
"lore_sn" = ["lore_sn-permit_token"]

[init_call_args]
"lore_sn-permit_token" = [
  "0x0", # messaging/piltover address
  "0x0", # appchain address
  "0x0", # cartridge address
]

[migration]
skip_contracts = [
  "fact_registry_mock", # deployed manually
]
