[world]
seed = "lore"
name = ">LORE"
description = "> get started with LORE"

[namespace]
default = "lore"

[env]
rpc_url = "https://api.cartridge.gg/x/lore-v1/katana"
slot_name = "lore-v1"

account_address = "0x6677fe62ee39c7b07401f754138502bab7fac99d2d3c5d37df7d1c6fab10819"
private_key = "0x3e3979c1ed728490308054fe357a9f49cf67f80f9721f44cc57235129e090f4"
world_address = "0x3ea2fa8bf5649c0e6fdec0482a23bdf760ec1add97c464c518b4e4bd9ab9f08"

[writers]
"lore" = ["lore-prompt", "lore-designer"]
