[package]
name = "lore"
cairo-version = ">=2.12.2"
version = "0.1.1"
edition = "2024_07"
experimental-features = ["associated_item_constraints"]

[cairo]
sierra-replace-ids = true
inlining-strategy = "avoid"

[scripts]
migrate = "sozo build && sozo migrate apply"

[dependencies]
starknet = ">=2.12.2"
dojo = "1.7.2"
achievement = { git = "https://github.com/cartridge-gg/arcade", rev = "a4de9f4c38814a19716b6c5f9cbd4213645e9cb1" }
origami_random = { git = "https://github.com/dojoengine/origami", tag = "v1.6.1" }
openzeppelin_token = { git = "https://github.com/OpenZeppelin/cairo-contracts", tag = "v1.0.0" }
openzeppelin_introspection = { git = "https://github.com/OpenZeppelin/cairo-contracts", tag = "v1.0.0" }
nft_combo = { git = "https://github.com/underware-gg/cairo-nft-combo", branch = "scarb_2.12.2" }

[dev-dependencies]
cairo_test = ">=2.12.2"
dojo_cairo_test = "1.7.2"

[tool.scarb]
allow-prebuilt-plugins = ["dojo_cairo_macros"]

[[target.starknet-contract]]
build-external-contracts = [
  "dojo::world::world_contract::world",
  "achievement::events::index::e_TrophyCreation",
  "achievement::events::index::e_TrophyProgression",
]
allowed-libfuncs-list.name = "experimental"

# debug contract size (max=81,920 felts)
# to be used with `sozo build --stats.by-tag`
# https://docs.starknet.io/resources/chain-info/
# uncomment this...
# sierra = true
# casm = true

# Dojo profiles
[profile.dev]
[profile.slot]
[profile.stage]
